apiVersion: awspca.cert-manager.io/v1beta1
kind: AWSPCAClusterIssuer
metadata:
  name: pca-cluster-issuer-ec
spec:
  arn: {{EC_CA_ARN}}
  region: {{REGION}}
  secretRef:
    namespace: default
    name: pca-secret
