apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pca-cluster-issuer-ec-cert
spec:
  subject:
    organizations:
    - aws
  dnsNames:
    - cluster-issuer-ec-example.com
  privateKey:
    algorithm: "ECDSA"
    size: 256
  secretName: pca-cluster-issuer-ec-cert-tls
  issuerRef:
    kind: AWSPCAClusterIssuer
    name: pca-cluster-issuer-ec
    group: awspca.cert-manager.io