apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pca-issuer-ec-cert
  namespace: default
spec:
  subject:
    organizations:
    - aws
  dnsNames:
    - issuer-ec-example.com
  privateKey:
    algorithm: "ECDSA"
    size: 256
  secretName: pca-issuer-ec-cert-tls
  issuerRef:
    kind: AWSPCAIssuer
    name: pca-issuer-ec
    group: awspca.cert-manager.io