kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: rsa-cert-4096
  namespace: default
spec:
  commonName: rsa-4096.example.com
  dnsNames:
    - rsa-4096.example.com
  duration: 2160h0m0s
  issuerRef:
    group: awspca.cert-manager.io
    kind: AWSPCAClusterIssuer
    name: example
  renewBefore: 360h0m0s
  secretName: rsa-cert-4096
  usages:
    - server auth
    - client auth
  privateKey:
    algorithm: "RSA"
    size: 4096
