apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pca-issuer-rsa-cert
  namespace: default
spec:
  subject:
    organizations:
    - aws
  dnsNames:
    - issuer-rsa-example.com
  privateKey:
    algorithm: "RSA"
    size: 2048
  secretName: pca-issuer-rsa-cert-tls
  issuerRef:
    kind: AWSPCAIssuer
    name: pca-issuer-rsa
    group: awspca.cert-manager.io
