kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: 0.0.0.0
  apiServerPort: 6443
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://kind-registry:5000"]
nodes:
- role: control-plane
  image: "kindest/node:v1.31.6@sha256:28b7cbb993dfe093c76641a0c95807637213c9109b761f1d422c2400e22b8e87"
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
        extraArgs:
            api-audiences: "kubernetes.svc.default,cluster.identifier.kubernetes.domain"
            service-account-issuer: "https://S3_BUCKET_NAME_PLACEHOLDER.s3.us-east-1.amazonaws.com/cluster/my-oidc-cluster"
            service-account-jwks-uri: "https://S3_BUCKET_NAME_PLACEHOLDER.s3.us-east-1.amazonaws.com/cluster/my-oidc-cluster/openid/v1/jwks"
            service-account-signing-key-file: "/etc/kubernetes/pki/sa.key"
