name: On Push to Main Branch

on:
  push:
    branches: [ main ]

concurrency:
  group: main-release
  cancel-in-progress: false

jobs:
  describe:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version: ${{ steps.describe.outputs.version }}
    steps:
    - name: Check out code
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      with:
        fetch-depth: 0
    - name: Describe commit
      id: describe
      run: echo "version=$(git describe --tags)" >> "$GITHUB_OUTPUT"

  beta:
    needs: describe
    permissions:
      id-token: write
      contents: read
    uses: './.github/workflows/publish-and-test.yml'
    with:
      version: ${{ needs.describe.outputs.version }}
      role: arn:aws:iam::783680406432:role/GithubActionsPublishRole-test-us-east-1
      public_repository: public.ecr.aws/z0d6s8x8/cert-manager-aws-privateca-issuer-test
      private_repository: 783680406432.dkr.ecr.us-east-1.amazonaws.com/eks/aws-privateca-issuer-test
      chart_branch: gh-pages-beta
      charts_url: https://raw.githubusercontent.com/${{ github.repository }}/gh-pages-beta
    secrets: inherit
