name: Publish and Test

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      account:
        required: true
        type: string
      stage:
        required: true
        type: string
      registry_alias:
        required: true
        type: string
      repository_suffix:
        required: false
        type: string
        default: ''
      chart_branch:
        required: true
        type: string
      charts_url:
        required: true
        type: string

jobs:
  publish:
    permissions:
      id-token: write
      contents: read
    uses: './.github/workflows/on-release.yml'
    with:
      version: ${{ inputs.version }}
      role: arn:aws:iam::${{ inputs.account }}:role/GithubActionsPublishRole-${{ inputs.stage }}-us-east-1
      public_repository: public.ecr.aws/${{ inputs.registry_alias }}/${{ github.repository_owner }}-${{ github.event.repository.name }}${{ inputs.repository_suffix }}
      private_repository: ${{ inputs.account }}.dkr.ecr.us-east-1.amazonaws.com/eks/${{ github.event.repository.name }}${{ inputs.repository_suffix }}
      chart_branch: ${{ inputs.chart_branch }}
      charts_url: ${{ inputs.charts_url }}
    secrets: inherit

  e2e:
    needs: publish
    strategy:
      fail-fast: false
      matrix:
        architecture: [ arm64, x86_64 ]
    permissions:
      id-token: write
      contents: read
    uses: './.github/workflows/on-safe-to-test-label.yml'
    with:
      architecture: ${{ matrix.architecture }}
      chart_repository: ${{ inputs.charts_url }}
      chart_version: ${{ inputs.version }}
      image_repository: public.ecr.aws/${{ inputs.registry_alias }}/${{ github.repository_owner }}-${{ github.event.repository.name }}${{ inputs.repository_suffix }}
